baseurl = "https://zdyxry.github.io"
title = "Yiran's Blog"
theme = "hugo-coder"

paginate = 50000

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "zdyxry"
disablePathToLower = true

googleAnalytics = 'G-G0433XDZ3V'

defaultContentLanguage = "zh-cn"  # 默认使用的语言
[Languages.zh-cn]
  languageCode = "zh-cn"



[permalinks]
  posts = '/:year/:month/:day/:title/'

[params]
  author = "Yiran Zhou"
  description = "John Doe's personal website"
  keywords = "blog,developer,personal"
  gravatar = "zdyxry@gmail.com"

  favicon_32 = "/images/yiran.png"
  favicon_16 = "/images/yiran.png"

  since = 2016

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  toc = true
  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/zdyxry/"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/zdyxry/"
[[params.social]]
  name = "NeoDB Book"
  icon = "fa fa-book fa-2x"
  weight = 3
  url = "https://neodb.social/users/zdyxry@mastodon.social/complete/book/"
[[params.social]]
  name = "NeoDB Movie"
  icon = "fa fa-film fa-2x"
  weight = 3
  url = "https://neodb.social/users/zdyxry@mastodon.social/complete/movie/"
[[params.social]]
  name = "RSS"
  icon = "fa fa-rss fa-2x"
  weight = 3
  url = "/atom.xml"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "Tags"
  weight = 2
  url = "tags/"
[[menu.main]]
  name = "Friends"
  weight = 3
  url = "friends/"
[[menu.main]]
  name = "About"
  weight = 4
  url = "about/"


[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "atom"
